name: 'With Docker'
description: 'Start a Docker container with the K development environment set up'
inputs:
  container-name:
    description: 'Docker container name to use'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    run: |
      set -euxo pipefail

      CONTAINER_NAME=${{ inputs.container-name }}
      TAG=runtimeverificationinc/${CONTAINER_NAME}
      DOCKERFILE=${{ github.action_path }}/Dockerfile

      K_VERSION=$(cat deps/k_release)
      RISC0_VERSION=$(cat deps/risc0_release)
      SP1_VERSION=$(cat deps/sp1_release)

      docker build .                               \
        --file ${DOCKERFILE}                       \
        --build-arg K_VERSION=${K_VERSION}         \
        --build-arg RISC0_VERSION=${RISC0_VERSION} \
        --build-arg SP1_VERSION=${SP1_VERSION}     \
        --tag ${TAG}

  - name: 'Run Docker container'
    shell: bash {0}
    run: |
      set -euxo pipefail

      CONTAINER_NAME=${{ inputs.container-name }}
      TAG=runtimeverificationinc/${CONTAINER_NAME}
      WORKDIR=/home/user

      SOCK=/var/run/docker.sock
      DOCKER_ID=$(getent group docker | cut -d: -f3)

      docker run                 \
        --name ${CONTAINER_NAME} \
        --rm                     \
        --interactive            \
        --tty                    \
        --detach                 \
        --user root              \
        --workdir ${WORKDIR}     \
        --volume ${SOCK}:${SOCK} \
        ${TAG}

      docker cp . ${CONTAINER_NAME}:${WORKDIR}
      docker exec ${CONTAINER_NAME} chown -R user:user ${WORKDIR}
      docker exec ${CONTAINER_NAME} /bin/bash -c "groupadd -g ${DOCKER_ID} host-docker && usermod -aG host-docker user"
