name: 'Test PR'
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality-checks:
    name: 'Code Quality Checks & Unit Tests'
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
      - name: 'Install Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 'Install uv'
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.7.8'
      - name: 'Run code quality checks'
        run: make check
      - name: 'Run pyupgrade'
        run: make pyupgrade
      - name: 'Run unit tests'
        run: make cov-unit

  integration-tests:
    name: 'Integration Tests'
    runs-on: [self-hosted, linux, normal]
    timeout-minutes: 15
    env:
      CONTAINER: zkevm-integration-${{ github.sha }}
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: ${CONTAINER}
      - name: 'Build K definitions'
        run: docker exec -u user ${CONTAINER} make kdist
      - name: 'Run integration tests'
        run: docker exec -u user ${CONTAINER} make cov-integration
      - name: 'Tear down Docker container'
        if: always()
        run: |
          docker stop --time=0 ${CONTAINER}
