name: 'Update Dependencies'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/riscv-semantics'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-deps:
    name: 'Update Dependency Versions'
    runs-on: ubuntu-24.04
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}

      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com

      - name: 'Install Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 'Install uv'
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.7.8'

      - name: 'Update uv files'
        run: |
          KRISCV_VERSION=$(cat deps/kriscv_release)
          sed -i 's!    "kriscv@git+https://github.com/runtimeverification/riscv-semantics.git@[v0-9\.]*"!    "kriscv@git+https://github.com/runtimeverification/riscv-semantics.git@v'${KRISCV_VERSION}'"!' pyproject.toml
          uv lock --upgrade
          git add pyproject.toml uv.lock && git commit -m "pyproject.toml: Sync Version ${KRISCV_VERSION}" || true

      - name: 'Update K release'
        run: |
          K_VERSION=$(uv run python3 -c 'import pyk; print(pyk.__version__)')
          echo ${K_VERSION} > deps/k_release
          git add deps/k_release && git commit -m "deps/k_release: Set Version ${K_VERSION}" || true

      - name: 'Push updates'
        run: git push
